"""fix otp keys table name

Revision ID: 8495206f3264
Revises: 9e56331f2cbd
Create Date: 2025-08-11 21:55:12.068566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8495206f3264'
down_revision: Union[str, None] = '9e56331f2cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp_key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otp_key', 'user_id', name='uq_otp_key_user_id')
    )
    op.create_index(op.f('ix_otp_keys_id'), 'otp_keys', ['id'], unique=False)
    op.create_index(op.f('ix_otp_keys_otp_key'), 'otp_keys', ['otp_key'], unique=True)
    op.drop_index('ix_opt_keys_id', table_name='opt_keys')
    op.drop_index('ix_opt_keys_otp_key', table_name='opt_keys')
    op.drop_index('uq_otp_key_user_id', table_name='opt_keys')
    op.drop_table('opt_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opt_keys',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('otp_key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='opt_keys_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_otp_key_user_id', 'opt_keys', ['otp_key', 'user_id'], unique=True)
    op.create_index('ix_opt_keys_otp_key', 'opt_keys', ['otp_key'], unique=True)
    op.create_index('ix_opt_keys_id', 'opt_keys', ['id'], unique=False)
    op.drop_index(op.f('ix_otp_keys_otp_key'), table_name='otp_keys')
    op.drop_index(op.f('ix_otp_keys_id'), table_name='otp_keys')
    op.drop_table('otp_keys')
    # ### end Alembic commands ###
